version: '3'
services:
  grafana:
    image: grafana/grafana
    container_name: muinfluxdb_grafana
    ports:
      - '172.16.2.116:3000:3000'
    user: '472:0'
    volumes:
      - './data/grafana:/var/lib/grafana'
    depends_on:
      - influxdb
  influxdb:
    image: influxdb:2.7.1
    container_name: influxdb-local
    volumes:
      - ./data/influxdb:/var/lib/influxdb2
      - ./config/influxdb:/etc/influxdb2
    ports:
      - '172.16.2.116:3001:8086'
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=password
      - DOCKER_INFLUXDB_INIT_ORG=organization
      - DOCKER_INFLUXDB_INIT_BUCKET=bucket
